#!/usr/bin/env bash

CACHE="$HOME/.cache/shader-blue-light"
SHADER="$HOME/.config/hypr/shaders/blue-light-filter.glsl"

if [[ -f "$CACHE" ]]; then
    hyprctl eval "hl.config({decoration = {screen_shader = ''}})"
    rm "$CACHE"
else
    hyprctl eval "hl.config({decoration = {screen_shader = '$SHADER'}})"
    touch "$CACHE"
fi